### ISSUE TITLE
Support for colored icons

### ISSUE THREAD

**Issue by MIvanchev** [mengelbrecht/lightline-bufferline#101]
Hey, I really love lightline-bufferline, this plugin does everything I need and more plus it's easily customizable. One thing I wish it supported are colored icons as offered by nvim-web-devicons. Perhaps I could provide a PR if you're interested. Regards and thanks for the work on this very valuable plugin.

**Comment by mengelbrecht** [comment]
Hi @MIvanchev, thank you for the kind words. If you provide a PR I would be happy to take a look at it.

**Comment by MIvanchev** [comment]
No probs, you did awesome work. In fact the fix should be made in lightline but after trying it out, it looked awful with solarized so there's barely any point :D
