### ISSUE TITLE
How to hide a buffer in bufferline filetype: terminal

### ISSUE THREAD

**Issue by hungpham3112** [mengelbrecht/lightline-bufferline#103]
![image](https://user-images.githubusercontent.com/75968004/159098519-53fa43ee-faa8-4621-af70-5f9727df3ffc.png)

When opening terminal, a buffer will show the name of terminal to. How to disable this only filetype: Terminal? Thanks in advanced.

**Comment by mengelbrecht** [comment]
I will have a look at it soon.

**Comment by mengelbrecht** [comment]
I added support for a custom buffer filter function in branch `feature/custom-filter-function`, which I plan to merge after some testing. You can try the feature branch and use this code to hide all neovim terminal buffers:
```viml
function LightlineBufferlineFilter(buffer)
   return getbufvar(a:buffer, '&buftype') !=# 'terminal'
 endfunction

 let g:lightline#bufferline#buffer_filter = "LightlineBufferlineFilter"
```

**Comment by hungpham3112** [comment]
I'm using vim-plug. I added this line but still can't use your snippet in this branch.
```
Plug 'https://github.com/mengelbrecht/lightline-bufferline.git', {'branch': 'feature/custom-filter-function'}
```

**Comment by mengelbrecht** [comment]
I merged the feature branch. The code should now work without switching branches. Please reopen this issue if it does not work.

**Comment by hungpham3112** [comment]
> I merged the feature branch. The code should now work without switching branches. Please reopen this issue if it does not work.

Thanks, it worked very well.
