### ISSUE TITLE
[Feature] Pin terminal buffer with current edit buffer.

### ISSUE THREAD

**Issue by hungpham3112** [mengelbrecht/lightline-bufferline#106]
In my use case, when I edit julia file, I usually have to work with a vertical terminal buffer on the right and my `1.jl` on the left. It's really convenient if have any way to pin the terminal buffer with `1.jl` file, `:bnext` to jump to `2.jl` and next buffer don't have the terminal in the right. In current state, every time I use `:bnext` I have to close the previous terminal and when come back to `1.jl`, I use `:vs | bpre` to find the terminal buffer again. 

I think this can become an ideal feature because it's practical and many people will like it. Thanks if you consider it and make it a new feature.

**Comment by mengelbrecht** [comment]
This plugin is only responsible for displaying the buffers in the lightline tabline. Buffer management and placement are not part of this plugin and I have no intention to change that.

You could write some custom functions in your vim config which automate the steps you do when you switch buffers.
