### ISSUE TITLE
Is it possible not to show `...` when there are enough space? 

### ISSUE THREAD

**Issue by voldikss** [mengelbrecht/lightline-bufferline#107]
![image](https://user-images.githubusercontent.com/20282795/165783894-35dc4d95-23ae-4940-83c1-938ed70dcf58.png)

As shown in the picture above, there is enough space in the right side but lightline-buffer show a `...` sign which is not reasonable. 

So how to make buffline use all the space of tabline?

Or can you add an option to disable `...` behavior?

:pray: Please help

**Comment by mengelbrecht** [comment]
Hi @voldikss,

I added an option to disable the "more buffers" indicator. You can now use this setting to disable it:
```viml
let g:lightline#bufferline#disable_more_buffers_indicator = 1
```
