### ISSUE TITLE
Add ability to set max width

### ISSUE THREAD

**Issue by dkaszews** [mengelbrecht/lightline-bufferline#108]
Hi! I have been experimenting in putting the buffers into statusline instead of bufferline, and it works great until you open too many buffers.

![Screenshot_20220617-173406~3](https://user-images.githubusercontent.com/26599495/174357779-f8571e3d-58dd-48db-aee6-d24baa896201.jpg)
![Screenshot_20220617-173500~3](https://user-images.githubusercontent.com/26599495/174357784-e082cfe1-d025-45a1-a200-35024d1d6f83.jpg)

I narrowed it down to hardcoded `&columns` when calculating how many buffers can fit on screen. I replaced it with a setting that defaults to `return &columns`, but can also be overridden with a custom value or function. Since my statusline is entirely composed of components whose width I can easily calculate, it works great. 

![Screenshot_20220617-203255~2](https://user-images.githubusercontent.com/26599495/174357785-ca108a80-3f1b-4010-96ca-694f3ff50a3f.jpg)
![Screenshot_20220617-200444~2](https://user-images.githubusercontent.com/26599495/174357786-5fa7857a-e7f0-4dc6-9d82-8166bea8705e.jpg)

**Let me know if such usecase fits this plugin, if so I will open a PR**. Thanks for the project and quality code, it would be much harder to patch if `&columns` was all over the place instead of passed as argument.

**Comment by mengelbrecht** [comment]
Hi @dkaszews, I created PR #109 which should implement your suggestion. Does it solve your use-case?

**Comment by dkaszews** [comment]
@mengelbrecht Looks good, it's pretty much identical code to the one I wrote myself :)
