### ISSUE TITLE
Buffer reordering

### ISSUE THREAD

**Issue by dkaszews** [mengelbrecht/lightline-bufferline#118]
It would be very useful to be able to reorder buffers, so that you can keep the buffers you are actively working on close together and in some logical order, and quickly switch between them with `go_next/previous`.

Looking at possible implementation, since every information comes from `filtered_buffers()` (great job keeping your code organized!), then sticking a `sort()` at the end of it should work fine. For the ordering function, we can keep a dict with vim buffer ids and priority, which also defaults go buffer id if not given:
```viml
function get_buffer_priority(buffer)
    if !has_key(s:priorities)
        let s:priorities[a:buffer] = a:buffer
    endif
    return s:priorities[a:buffer]
endfunction
```

Then, if you want to move a buffer, you simply swap its priority with another one. Example:

1. Open files A, B, C
2. They get assigned priorities equal to buffer ids: `{ A: 1, B: 2, C: 3 }`
3. Sorting by priority results in same order ABC
4. Swap priority of A and B: `{ A: 2, B: 1, C: 3 }`
5. Sorting by priority now results in BAC

If worried about cost of sorting a large number of buffers, we can skip sorting if user has never called any reordering function, as tracked by a flag. This flag can also be reset if the order is returned to default (each priority is equal to buffer id).

**Comment by dkaszews** [comment]
I have a draft at https://github.com/dkaszews/lightline-bufferline/pull/1 , as it uses #117 as a base (no real dependencies, just some helper functions already implemented there). I will open a MR here after #117 is either merged or rejected.

I opened 100 buffers and measured time elapsed in `lightline#bufferline#buffers()`, on my Raspberry Pi 4B it went from 109ms to 123ms, so optimization I mentioned is not necessary. With more realistic 10 buffers, both take 20ms. Since the sort is at the very end, only the number of buffers actually shown in tabline matters, so ones that are hidden or from different category (#117) don't affect performance.

**Comment by dkaszews** [comment]
[Screen recording 2022-12-11 18.33.53.webm](https://user-images.githubusercontent.com/26599495/206919353-6092255c-b623-4446-be78-8dc38e3fac89.webm)

**Comment by ranelpadon** [comment]
@dkaszews Thanks for implementing this feature! Been wanting this for some time since I frequently re-order my Tmux windows, and wanted to do it with Vim buffers as well. Surprised and glad that it's now in `lightline-bufferline`. Cheers

**Comment by dkaszews** [comment]
@ranelpadon Really happy to have helped! It was a natural feature to expect, same as you might reorder tabs in a browser. The tricky part was how to implement it in a stable way, fortunately the idea of swapping the buffer ids via map worked so elegantly. Plus I could flex my maths skills by calling it a symmetric group 😁
