### ISSUE TITLE
My bufferline doesn't show multiple buffers

### ISSUE THREAD

**Issue by jy-gh** [mengelbrecht/lightline-bufferline#121]
I'm having trouble seeing a bufferline with a minimal example. Perhaps I have mis-configured it, as it doesn't look anything like your example.

Here's my entire `.vimrc` (I removed everything to test this):

`" -----------------------------------------------------------------------
" Pathogen
" -----------------------------------------------------------------------
call pathogen#infect()
syntax on
filetype plugin on
filetype indent on

" -----------------------------------------------------------------------
"  Leader
" -----------------------------------------------------------------------
let mapleader=","

" -----------------------------------------------------------------------
" lightline-bufferline
" -----------------------------------------------------------------------
set showtabline=2
let g:lightline#bufferline#show_number  = 1
let g:lightline#bufferline#shorten_path = 0
let g:lightline#bufferline#unnamed      = '[No Name]'
let g:lightline#bufferline#disable_more_buffers_indicator = 1
let g:lightline#bufferline#show_number = 1

let g:lightline = {
      \ 'colorscheme': 'one',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'tabline': {
      \   'left': [ ['buffers'] ],
      \   'right': [ [] ]
      \ },
      \ 'component_expand': {
      \   'buffers': 'lightline#bufferline#buffers'
      \ },
      \ 'component_type': {
      \   'buffers': 'tabsel'
      \ }
      \ }
`

Here's the output of `vim --version`:

`VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 28 2023 23:42:35)
macOS version - x86_64
Included patches: 1-1276
Compiled by MacPorts
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +find_in_path      +mouse_xterm       +tcl
+arabic            +float             +multi_byte        +termguicolors
+autocmd           +folding           +multi_lang        +terminal
+autochdir         -footer            -mzscheme          +terminfo
-autoservername    +fork()            +netbeans_intg     +termresponse
+balloon_eval      +fullscreen        +num64             +textobjects
+balloon_eval_term +gettext           +odbeditor         +textprop
+browse            -hangul_input      +packages          +timers
++builtin_terms    +iconv             +path_extra        +title
+byte_offset       +insert_expand     +perl              +toolbar
+channel           +ipv6              +persistent_undo   +transparency
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
-cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
+file_in_path      +mouse_urxvt       -tag_any_white
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/opt/local/MacVim.app/Contents/Resources/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -DMACOS_X -DMACOS_X_DARWIN -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -o Vim -lncurses -liconv -lintl -framework AppKit -L/opt/local/lib -llua -L/opt/local/lib -Wl,-headerpad_max_install_names -fstack-protector-strong -L/opt/local/lib/perl5/5.34/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -L/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/config-3.11-darwin -lpython3.11 -framework CoreFoundation -L/opt/local/lib -ltcl8.6 -lz -framework CoreFoundation -lruby.3.0 -L/opt/local/lib
`

I moved every plugin except for lightline.vim and lightline-bufferline out of my .vim/bundle directory.

Here's what I see:
![lightline-bufferline](https://user-images.githubusercontent.com/22357499/230729621-d99cf550-70a8-4120-8d66-96ec3613bd97.jpg)

**Comment by mengelbrecht** [comment]
Hi @jy-gh,

your configuration works for me, I see the bufferline. However, I tested it with [vim-plug](https://github.com/junegunn/vim-plug) instead of pathogen.
Are you sure that your pathogen configuration is working?

You can check if lightline.vim is loaded by entering the following command:
```viml
:call lightline#error("test")
```
That command should print a message `lightline.vim: test`.

If that succeeds you can check if lightline-bufferline is loaded by opening two (or more) buffers.
Then you can use the following command to cycle through the buffers (this should work even if the bufferline is not visible):
```viml
:call lightline#bufferline#go_next()
```

**Comment by jy-gh** [comment]
Hi @mengelbrecht, and thank you for your response.

I have many plugins installed, so Pathogen seems to work. 

Note that for all my comments and screenshots from here down I'm using my full-blown `.vimrc` with all my current plugins (24 by my count), not the minimal setup I had when I wrote the initial issue, but the behavior seems the same.

I did try the `:call lightline#error("test")`

Here's what I see, which I think is correct behavior:

![call_lightline_error](https://user-images.githubusercontent.com/22357499/230779338-85fa2807-7cba-4658-b53a-fa61e4daeae2.jpg)

I am also able to cycle through buffers using `:call lightline#bufferline#go_next()`.

As you can see from this screenshot, I have two buffers open, yet only one is displayed in the buffer list (note that `:bn`, `:bd`, and other buffer commands work):

![2_buffers](https://user-images.githubusercontent.com/22357499/230779401-3a1a66c8-c275-492f-afb8-3b037dc8e5cb.jpg)

I expected to see something like this:

![bufferline_example](https://user-images.githubusercontent.com/22357499/230779513-46fabbb9-da21-43b3-81b9-bb8000153c74.jpg)

Is there a enable/make visible command (for either lightline or lightline-buffer line) or perhaps a Vim setting that I'm missing? Just to be sure, I nuked my lightline directory and reinstalled from https://github.com/itchyny/lightline.vim, and I still get the same behavior.

**Comment by mengelbrecht** [comment]
I just noticed that this is most likely solved by the second entry of the [FAQ](https://github.com/mengelbrecht/lightline-bufferline#faq).
You can disable the graphical MacVim tabline rendering by setting this option in your vim config:
```viml
set guioptions-=e
```

**Comment by jy-gh** [comment]
Hi @mengelbrecht. That does fix it. I actually saw that and tried it, to no avail. I think I didn't have `set showtabline=2` set then, so when I used it, it didn't help, and then after that I added (and kept) `set showtabline=2` without re-trying `set guioptions-=e`.

My bad either way. Thank you!

**Comment by mengelbrecht** [comment]
Glad I could help :-)
