### ISSUE TITLE
Change setup after loaded

### ISSUE THREAD

**Issue by pablogipi** [mengelbrecht/lightline-bufferline#122]
Hello.
Thanks for this great plugin for vim.
I have been trying to do some tweaks after the plugin is loaded, basically I want to enable icons using:
g:lightline#bufferline#unicode_symbols
g:lightline#bufferline#enable_devicons

But I want to do this using a script called during _VimEnter_, the idea is to have the default setup and the in VimEnter checking GUI is running and enable all the fancy stuff.
I'm am doing something similar with lightline, after doing my changes I can run their funcitons to enable/disable to force a reload of the plugin.
However with lightline-bufferline I haven't been able to figure out how to enable/disable the plugin so it can get new changes in config that happened after the plugin was initially loaded.
Any idea?

Thanks.

**Comment by mengelbrecht** [comment]
Hi @pablogipi

I added support for reloading the configuration using the new function `lightline#bufferline#reload()`.

Please let me know if this solves your use-case.

**Comment by pablogipi** [comment]
Works like a charm
Thanks!!!
