### ISSUE TITLE
Last commit 8a2e7ab broke things for me.

### ISSUE THREAD

**Issue by PatrBal** [mengelbrecht/lightline-bufferline#124]
I am using Neovim 0.9.1
As I want to make buffers in bufferline clickable, I had the three following lines in my .vimrc
```
let g:lightline#bufferline#clickable = 1
let g:lightline = {}
let g:lightline.component_raw = {'buffers': 1}
``` 
according to the README. It used to work like a charm, but commit 8a2e7ab broke things for me.
After that commit, my bufferline shows no buffers any more.
When I comment out the 2 lines:
```
let g:lightline = {}
let g:lightline.component_raw = {'buffers': 1}
```
in my .vimrc, I recover a normal bufferline, except that it is not clickable anymore.
Any idea to troubleshoot?
Thanks in advance.

**Comment by mengelbrecht** [comment]
Thanks for the report @PatrBal. I found the bug and fixed it. Please update the plugin and try again.

**Comment by PatrBal** [comment]
Fixed. Thank you very much.
