### ISSUE TITLE
Incorrect buffer length calculation

### ISSUE THREAD

**Issue by dkaszews** [mengelbrecht/lightline-bufferline#126]
To reproduce:
1. In `autoload/lightline/bufferline.vim`, add the following code in the third line, save and `:source %`:
    ```viml
    let l:sum = s:sum(l:before_lengths) + s:sum(l:current_lengths) + s:sum(l:after_lengths)
    echo printf('expected: %d, actual: %d', l:sum, wincol())
    ```
1. Align cursor with the end of the bufferline, `set virtualedit=all cursorcolumn` may be helpful
1. `:call lightline#bufferline#buffers()` to see updated values

In my case, with a couple of buffers opened, I see `expected: 72, actual: 64`. The difference seems to be twice the number of buffers. If I change the `+ 4` in `s:get_buffer_names` to `+ 2`, the value is correct.

The actual value is dependent on `g:lightline.tabline_(sub)separator` settings, I have both set to empty strings so each buffer is surrounded only by two spaces (e.g. ` aaa  bbb  ccc `), hence the +2. The `+4` is only correct if separators and subseparators are both two character strings. If they are not equal to each other, then the actual length differs depending on whether the current buffer is first or last, or in the middle, causing jitter when switching.

This is currently not that big of an issue, only affecting which buffers are displayed (e.g. show ` aaa  bbb  ... ` while ` aaa  bbb  ccc  ... ` would just barely fit). I am however trying to implement bufferline centering by prepending results with an extra string with an appropriate number of spaces, where it is visibly off-center due to incorrect width calculations.

A quick fix would be to change `+ 4` to `+ 2 + len(g:lightline.tabline_separator.left)`, (or `.right` if `right_aligned`, plus fallback and defaults). I would be willing to ignore the case when they are not, and just add a warning and/or FAQ to keep them the same.

**Comment by mengelbrecht** [comment]
Thanks for your report @dkaszews.

I tweaked the buffername length calculation a bit. It is still not perfect since the length of the "more buffers" fake-buffer is not calculated correctly in all cases.

You can find the code on the following branch: `feature/improve_buffer_display`.
It would be great if you could test it and let me know if it improves the buffername calculation for you.

**Comment by dkaszews** [comment]
Thanks, I'll play around with it once I'm back from vacation :)

**Comment by dkaszews** [comment]
I have taken a look at your code, played around and here's what I found:

1. Two spaces always surround name, so constant `+2`
2. `separator` is used between `current` and `before/after` sections
3. `subseparator` is used between elements inside `before/after` sections (also technically `current`, but there's never more than one of those)

While you are technically correct that `separator` would also be used before/after the tabline as a whole, it is only in case where there are other components, where you need to override `lightline#bufferline#max_width` anyways.

Your `lightline_(sub)separator_len` looks incorrect as `lightline` is configured via a single dict instead of distinct options, plus the defaults are `''` and `'|'` according to `lightline` documentation. This code should be better with a bit more error checking:

```viml
let l:align = s:right_align ? 'right' : 'left'
let l:GetSeparator = { sub, def -> get(g:lightline, 'tabline_' .. sub .. 'separator',
  \ get(g:lightline, sub .. 'separator', { l:align: def }))[l:align] }
let s:separator_len = len(GetSeparator('', ''))
let s:subseparator_len = len(GetSeparator('', '|'))
```

I'll have to take a looks at `s:select_fitting_buffers` algorithm to check if it would be possible to calculate real width on the fly instead of precomputing it, as that would be my preferred way to do centering:

```viml
function s:sum_width(list)
  return len(a:list) == 0 ? 0
    \ : s:sum_len(a:list) + s:separator_len + s:subseparator_len * (len(a:list) - 1)
endfunction

...
let l:width = s:sum_width(l:buffers[0]) + len(l:buffers[1][0]) + s:sum_width(l:buffers[2])
```

If you'd prefer keeping the current logic of precomputing it in `s:get_buffer_names`, then I think the better way would be to:

1. Keep `current` without separator, as it depends on its position
2. In `before`, add `separator_len` to last and `subseparator_len` to all else
3. In `after`, add `separator_len` to first and `subseparator_len` to all else

**Comment by dkaszews** [comment]
I created alternative implementation in #128, tested it to work with different (sub)separators in bunch of cases: current first, middle, last, none (hidden or filtered out).

**Comment by mengelbrecht** [comment]
Thanks for your contribution. Merged :-)
