### ISSUE TITLE
The plugin does not support Gvim

### ISSUE THREAD

**Issue by HuaYishu** [mengelbrecht/lightline-bufferline#129]
In the Window10, I configured my `_vimrc` file, and restarted Gvim, but the bufferline did not appear . Then, I configured `set showtabline=2`, and the tabline appeared but no more change, which is just a tabline. However, when I open vim in the terminal, it works. So, I think this plugin is very good, but it seems not to support Gvim. I have no idea whether this is a problem with the plugin or lightline itself.

Here is a picture related to Gvim.
![any](https://github.com/mengelbrecht/lightline-bufferline/assets/106532450/4b7b98c2-bb7f-4ba5-844f-9910973aae66)

**Comment by mengelbrecht** [comment]
This is most likely solved by the second entry of the [FAQ](https://github.com/mengelbrecht/lightline-bufferline#faq).
You can disable the graphical gVim tabline rendering by setting this option in your vim config:
```viml
set guioptions-=e
```

**Comment by HuaYishu** [comment]
Wonderful! Thanks a lot, it works! Next time I will read the readme more carefully(≧﹏ ≦).

**Comment by mengelbrecht** [comment]
Glad you got it working 😊
