### ISSUE TITLE
shorten_path isn't working

### ISSUE THREAD

**Issue by andreas-bulling** [mengelbrecht/lightline-bufferline#17]
Hi,

I am using the latest version of neovim and lightline(-bufferline) on Mac and while the plugin works fine in general, the option shorten_path doesn't seem to have any effect. Any ideas?

**Comment by mengelbrecht** [comment]
The `shorten_path` option is active by default. It can be disabled by placing the following line in your vim config
```vim
let g:lightline#bufferline#shorten_path = 0
```

With the `shorten_path` option enabled the file path is displayed shortened. E.g. opening the file `/usr/local/etc/bash_completion.d/tmux` displays `/u/l/e/b/tmux` in the bufferline.
If the `shorten_path` option is disabled the same file is displayed as `/usr/local/etc/bash_completion.d/tmux` in the bufferline.

What is displayed in the bufferline if you open a file? Do you have any other settings of lightline-bufferline configured?

**Comment by andreas-bulling** [comment]
Thanks @mgee for your quick reply! I see - I was under the assumption that, similar to other plugins, with this option set the path is removed completely so that only the filename remains.

Maybe that could be an interesting and easy to implement improvement?
`let g:lightline#bufferline#shorten_path = 0` disabled
`let g:lightline#bufferline#shorten_path = 1` path is shortened
`let g:lightline#bufferline#shorten_path = 2` path is completely removed, only filename is shown

**Comment by mengelbrecht** [comment]
The option `filename_modifier` can be used to customize the buffer names. To only show the filename without path use the option:
```vim
let g:lightline#bufferline#filename_modifier = ':t'
```

You can see the available options using `:help filename-modifiers` in vim.
By default this plugin uses the setting `:.` which makes the filename relative to the current directory if possible.

**Comment by andreas-bulling** [comment]
Great, thanks a lot!
