### ISSUE TITLE
vim-devicons integration

### ISSUE THREAD

**Issue by kablondino** [mengelbrecht/lightline-bufferline#18]
As of now, I cannot find a way to have vim-devicons into this bufferline. I am attempting to do it in the same manner as the status line given by the instructions of vim-devicons. Is there any plans to integrate it?

**Comment by polyzen** [comment]
An implementation from another plugin: https://github.com/taohexxx/lightline-buffer/commit/22b6e12f14f36b2456b61a35694a10ba313072b0

**Comment by mengelbrecht** [comment]
I added support for vim-devicons, to try it use this setting:
```vim
let g:lightline#bufferline#enable_devicons = 1
```

Please let me know if it works for you :-)

**Comment by kablondino** [comment]
It works wonderfully, thanks.
