### ISSUE TITLE
Hide path?

### ISSUE THREAD

**Issue by fdietze** [mengelbrecht/lightline-bufferline#19]
Is there a way to hide the file path and only show the basename of the file?

**Comment by mengelbrecht** [comment]
The option `filename_modifier` can be used to customize the buffer names. To only show the filename without path use the option:
```vim
let g:lightline#bufferline#filename_modifier = ':t'
```

You can see the available options using `:help filename-modifiers` in vim.
By default this plugin uses the setting `:.` which makes the filename relative to the current directory if possible.

(Relates to #17)
