### ISSUE TITLE
Renumbering buffers and go to buffer command

### ISSUE THREAD

**Issue by tiberiuichim** [mengelbrecht/lightline-bufferline#2]
I wonder if it's possible to implement the "2. Mappings" feature of BufTabLine, https://github.com/ap/vim-buftabline/blob/master/doc/buftabline.txt

With this, the buffers would be renumbered and an easy  <Leader><number> can be mapped to switch to that tab number. This increases the functionality of the plugin and what we get out of the visual buffers indicators.

**Comment by mengelbrecht** [comment]
Sure it is possible. Working on it right now :-)

**Comment by mengelbrecht** [comment]
@tiberiuichim does #3 fit your usecase?

**Comment by tiberiuichim** [comment]
@mgee It works perfect! Thank you very much!
