### ISSUE TITLE
Place Tabs on Status Bar

### ISSUE THREAD

**Issue by starifly** [mengelbrecht/lightline-bufferline#22]
Is there any way to place tabs in the status bar rather the actual tab bar?

I like having my buffers on top since I have more space and I always have more buffers than tabs.

Just like the image below:
![tabline](https://user-images.githubusercontent.com/2003879/43378251-3d95a57a-93f8-11e8-95f5-b930bb9f3277.png)
Also, is there a way to add the powerline symbols to the tab as well? For example, from the image above, 'Tab1' is the current tab and should be highlighted. Basically I'd like it to look exactly like the buffers above.

**Comment by if2012** [comment]
#https://github.com/itchyny/lightline.vim/issues/313

**Comment by mengelbrecht** [comment]
Your issue is better suited in the lightline project since this plugin only provides the functionality to add a bufferlist to lightline. I saw that you already opened an issue in the lightline repository https://github.com/itchyny/lightline.vim/issues/313 therefore I am closing this one.
