### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by redreceipt** [mengelbrecht/lightline-bufferline#24]
Have the exact lines from your example in my .vimrc and it's not showing open buffers. Any insight?

my `.vimrc`:
```
" lightline-bufferline integration
let g:lightline#bufferline#unnamed	= '[No Name]'
let g:lightline						= {}
let g:lightline.tabline				= {'left': [['buffers']], 'right': [['close']]}
let g:lightline.component_expand	= {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type		= {'buffers': 'tabsel'}
```

my Vim window:
![screen shot 2018-09-24 at 1 12 09 pm](https://user-images.githubusercontent.com/2659478/45967328-a9b97400-bffb-11e8-9291-db40f9008a5d.png)

**Comment by mengelbrecht** [comment]
Do you have the following option set in your `.vimrc`:
```set showtabline=2```?

**Comment by redreceipt** [comment]
That fixed it, thanks. Is there a way to make it match the status line in color? The bright white by default is too much. Your sample image looks much nicer than mine.

<img width="950" alt="screen shot 2018-09-24 at 9 58 43 pm" src="https://user-images.githubusercontent.com/2659478/45988456-0c832d80-c045-11e8-8edd-7323232b1503.png">

**Comment by mengelbrecht** [comment]
You are using the default lightline colorscheme `powerline`. Changing it to`wombat` or `one` should improve the colors:
```vim
let g:lightline.colorscheme = "one"
```

Guessing from your screenshots it looks like you might be using `gruvbox` as editor colorscheme.
In case you have https://github.com/morhetz/gruvbox installed you can change the lightline colorscheme to gruvbox using the following settings in your `.vimrc`:
```vim
set background=dark
colorscheme gruvbox
let g:lightline.colorscheme = "gruvbox"
```

**Comment by redreceipt** [comment]
I am using gruvbox, thank you!
