### ISSUE TITLE
Option let g:lightline not working

### ISSUE THREAD

**Issue by lmontigny** [mengelbrecht/lightline-bufferline#25]
In my .vimrc:
Plug 'mgee/lightline-bufferline'
Plug 'edkolev/tmuxline.vim'           " Change tmux bar color
...
let g:lightline.tabline          = {'left': [['buffers']], 'right': [['close']]}
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}

Bash output:
line   55:
E121: Undefined variable: g:lightline
line   56:
E121: Undefined variable: g:lightline
line   57:
E121: Undefined variable: g:lightline

**Comment by mengelbrecht** [comment]
It seems the lightline plugin is missing in your vim config:
```vim
Plug 'itchyny/lightline.vim'
```

**Comment by lmontigny** [comment]
Yep, thanks!
