### ISSUE TITLE
Buffers not updated on badd

### ISSUE THREAD

**Issue by ddorstijn** [mengelbrecht/lightline-bufferline#26]
When adding a buffer using :badd, the bufferline is not updated until I switch buffers.

**Comment by mengelbrecht** [comment]
Sorry for the delay. I will investigate how this can be solved.

**Comment by mengelbrecht** [comment]
This turned out to be an issue in vim itself which you can track here: https://github.com/vim/vim/issues/3770

Until there is another solution you can use the following workaround which forces a redraw of the tabline when adding a buffer:
```vim
au BufAdd * let &tabline = &tabline
```

**Comment by ddorstijn** [comment]
Thanks for the guide in the right direction

**Comment by mengelbrecht** [comment]
In vim >= 8.1.0706 you can use the following solution:
```vim
au BufAdd * redrawtabline
```
