### ISSUE TITLE
Show both buffer number and ordinal number

### ISSUE THREAD

**Issue by sandangel** [mengelbrecht/lightline-bufferline#27]
Hi, is there a way for me to show both the ordinal number and buffer number?
I could map the ordinal number to the unicode character, and use `<leader>1 ~ 0` to quickly go to the buffer by ordinal number, with a buffer that ordinal number is 11, I will use the buffer number with `[N]<space>` to quickly go there.

**Comment by mengelbrecht** [comment]
Resolved by #28
