### ISSUE TITLE
 Can  add an option to cancel the path display?

### ISSUE THREAD

**Issue by glepnir** [mengelbrecht/lightline-bufferline#30]
## Feature
The current state, even if I use short_path, but it is too long to look ugly, the airline's tabline can only display the file name, so I want to add an option.
![2321](https://user-images.githubusercontent.com/41671631/52127811-304b2580-266e-11e9-93b9-5c637bf72b90.png)

**Comment by mengelbrecht** [comment]
See https://github.com/mengelbrecht/lightline-bufferline/issues/17#issuecomment-365929149

In short: `let g:lightline#bufferline#filename_modifier = ':t'` should do the trick.

**Comment by glepnir** [comment]
> See [#17 (comment)](https://github.com/mengelbrecht/lightline-bufferline/issues/17#issuecomment-365929149)
> 
> In short: `let g:lightline#bufferline#filename_modifier = ':t'` should do the trick.

it works great
