### ISSUE TITLE
can add vim-devicons support?

### ISSUE THREAD

**Issue by glepnir** [mengelbrecht/lightline-bufferline#31]
## Feature
Add ryanoasis/vim-devicons in bufferline

**Comment by mengelbrecht** [comment]
To enable vim-devicons support use this setting:
```viml
let g:lightline#bufferline#enable_devicons = 1
```

**Comment by glepnir** [comment]
> To enable vim-devicons support use this setting:
> 
> ```viml
> let g:lightline#bufferline#enable_devicons = 1
> ```
it works well
