### ISSUE TITLE
Adding a option to disable showing paths

### ISSUE THREAD

**Issue by wanchaol** [mengelbrecht/lightline-bufferline#32]
I know there's a shorten path option, but it would be really nice to have an option that disable showing the paths, but only show the file names, is it already available or that's something that need to implement?

**Comment by mengelbrecht** [comment]
See #30. I also added an entry in the FAQ in df868161462e87cc103ac543beacfc11f58b861f.

**Comment by wanchaol** [comment]
@mengelbrecht Thanks!
