### ISSUE TITLE
Support tab next, previous, and close

### ISSUE THREAD

**Issue by wanchaol** [mengelbrecht/lightline-bufferline#33]
Can this support things like lightline#bufferline#next, lightline#bufferline#prev, and lightline#bufferline#close ?

**Comment by mengelbrecht** [comment]
You can map keys to the `bprev`, `bnext` and `bdelete` commands to achieve this.

Here is an example which you can adapt and use in your vim config:
```viml
" Close the buffer using Ctrl+x
nnoremap <silent> <C-x> :bdelete<CR>

" Switch to the previous buffer using Ctrl+h
nnoremap <silent> <C-h> :bprev<CR>

" Switch to the next buffer using Ctrl+l
nnoremap <silent> <C-l> :bnext<CR>
```
