### ISSUE TITLE
No devicons with filename modifier ':t:r' 

### ISSUE THREAD

**Issue by F4IL3D** [mengelbrecht/lightline-bufferline#35]
If _':t:r'_ as filename modifier is used, the devicons are not showing.
I could fix this by changing the following line 

`let l:name = WebDevIconsGetFileTypeSymbol(l:name) . ' ' . l:name`

to this

`let l:name = WebDevIconsGetFileTypeSymbol(fnamemodify(bufname(a:buffer), ':t')) . ' ' . l:name`.

I think this has the advantage that the devicons are determined independently of the used filename modifiers.
Sorry if my solution should not be good but I'm new to dealing with Vim and VimL

Thanks for the great plugin.

**Comment by mengelbrecht** [comment]
Thanks! I fixed it using your suggestion.
