### ISSUE TITLE
Vim location list / quickfix is visible in bufferline

### ISSUE THREAD

**Issue by F4IL3D** [mengelbrecht/lightline-bufferline#36]
The location list / quickfix buffer is visible in the bufferline.

![image](https://user-images.githubusercontent.com/48415231/54090015-acbcdc80-436f-11e9-8928-e3990afc4ac1.png)

I could fix this by changing the following line

`return bufexists(a:i) && buflisted(a:i)`

to this

`return bufexists(a:i) && buflisted(a:i) && !(getbufvar(a:i, '&filetype') ==# 'qf')`

Sorry if my solution should not be good but I'm new to dealing with Vim and VimL

Thanks for the great plugin.

**Comment by mengelbrecht** [comment]
Thanks! I fixed it using your suggestion.
