### ISSUE TITLE
you forgot " " in show_number

### ISSUE THREAD

**Issue by trbjo** [mengelbrecht/lightline-bufferline#37]
In bufferline.vim line 48, you forgot to add a space. 

Now it looks like this:
`    let l:name = s:get_from_number_map(a:i + 1) . l:name`
It should look like this 
`    let l:name = s:get_from_number_map(a:i + 1) . ' ' . l:name`

**Comment by mengelbrecht** [comment]
Thanks. I made the separator customizable via the new setting `number_separator`.
This separator is used in all options of the `show_number` setting.
