### ISSUE TITLE
Reverse tabs order

### ISSUE THREAD

**Issue by kureijir** [mengelbrecht/lightline-bufferline#38]
At the moment, if I place `buffers` component on the right side (either on tabline or statusline), it get 'reversed' like this:
![current](https://user-images.githubusercontent.com/21220094/63741212-52342000-c8be-11e9-8218-66eb2ff329a5.png)

My quick fixes:

1. Change `lightline#bufferline#buffers`
```vim
function! lightline#bufferline#buffers()
  ...
  "return s:select_buffers(l:before, l:current, l:after)
  return s:select_buffers(l:after, l:current, l:before)
endfunction
```
![fix1](https://user-images.githubusercontent.com/21220094/63741143-f49fd380-c8bd-11e9-9805-e7aa4bc552b0.png)

2. Change `s:get_buffer_names`
```vim
function! s:get_buffer_names(buffers, from, to)
  ...
  "return l:names
  return reverse(l:names)
endfunction
```
![fix2](https://user-images.githubusercontent.com/21220094/63741264-87d90900-c8be-11e9-9b93-3e8532381c6c.png)

3. BONUS: If both hacks applied, and `buffers` component is on the left side, we'll have this
![both](https://user-images.githubusercontent.com/21220094/63741648-2023bd80-c8c0-11e9-82a1-5f96f4dec9d2.png)

Though, for my use case only the first one is needed. And of course, if implemented, they would need to be manually enabled by user through config variable.

I'd like to hear your thoughts on this.

**Comment by mengelbrecht** [comment]
Have a look at #39 for a possible solution.

If you use a right aligned bufferline you can set `let g:lightline#bufferline#right_aligned = 1` to ensure that the buffers are correctly ordered.
If you want to reverse the buffers you can set `let g:lightline#bufferline#reverse_buffers = 1`.

Does this cover your use-cases?

**Comment by kureijir** [comment]
Thank you for your quick work. Yes those two options are more than suffice.

One note: as you can see in the last screenshot in the OP, if a user ever want to have a reversed bufferline on the _left_ side, they would have to set both `g:lightline#bufferline#right_aligned` and `g:lightline#bufferline#reverse_buffers` to `1`, which is somewhat counterintuitive (_why enabling `right_aligned` when I want my bufferline on the left?_). You might want to make a note in README to avoid such confusion.

**Comment by mengelbrecht** [comment]
To get a reversed bufferline on the left side only `g:lightline#bufferline#reverse_buffers` has to be set to `1`. It should result in a bufferline as seen in the last screenshot. Can you check again if you really have to set `g:lightline#bufferline#right_aligned ` to `1` if you use it on the left side?

**Comment by kureijir** [comment]
Oh, my bad since I haven't tested before even commenting (I forgot that I could specify the plugin's gitbranch with vim-plug). Now I can confirm that everything is working as it should.

**Comment by mengelbrecht** [comment]
Thanks!
