### ISSUE TITLE
[Bug] lightline-bufferline doesn't handle very well more buffers than can be displayed at once

### ISSUE THREAD

**Issue by karlyeurl** [mengelbrecht/lightline-bufferline#4]
I genrated a lot of dummy files to quickly illustrate the issue, and opened them all at once.

If I try to reach one of the latter buffers (here, 2.txt), the selected buffer is on the screen and that is correct.
![2017-01-26-135114_958x529_scrot](https://cloud.githubusercontent.com/assets/3105484/22331961/8a1da87e-e3ce-11e6-9a1d-419d06df607e.png)

If I try to reach one of the buffers hidden by the < arrow (in this case, 14.txt), the bufferline does not update to display the selected buffer.
![2017-01-26-135102_958x529_scrot](https://cloud.githubusercontent.com/assets/3105484/22331962/8a20ade4-e3ce-11e6-96ca-f045a93464ee.png)

Thank you for creating that bufferline! I miss a feature or two from the airline bufferline (inactive splits shown as selected inactive buffers ([lightline-bufferline](https://cloud.githubusercontent.com/assets/3105484/22331987/bc4aee7e-e3ce-11e6-8c99-83ee00b46b0a.png) vs [airline](https://cloud.githubusercontent.com/assets/3105484/22332052/1a1cf128-e3cf-11e6-93dd-ea6562018e3f.png), mostly)), but in my search for lightweight but good-looking powerline/airline replacements, your project meets the requirements. :+1: for super readable code, I hope to have the time to look into it to tweak it to my liking.

**Comment by mengelbrecht** [comment]
Thanks for the report. I will have a look.
