### ISSUE TITLE
lightline-bufferline conflicts with vim-noscrollbar plugin

### ISSUE THREAD

**Issue by khughitt** [mengelbrecht/lightline-bufferline#40]
I noticed that when lightline-bufferline is used along-side of [vim-noscrollbar](https://github.com/gcavallanti/vim-noscrollbar), the buffer list at the top is no longer rendered properly, and instead, only a single buffer tab is displayed.

Relevant config:

```
# lightline / bufferline
let g:lightline = { 'colorscheme': 'ThemerVimLightline' }
let g:lightline.tabline          = {'left': [['buffers']], 'right': [['close']]}
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}
let g:lightline#bufferline#enable_devicons = 1
let g:lightline#bufferline#show_number  = 1

# vim-noscrollbar
Replace percent component of Lightline statusline
https://codeyarns.com/2017/10/25/how-to-add-noscrollbar-to-lightline/
let g:lightline = {
     \ 'component_function': {
     \   'percent': 'NoScrollbarForLightline'
     \ }
     \ }

Instead of % show NoScrollbar horizontal scrollbar
function! NoScrollbarForLightline()
   return noscrollbar#statusline()
endfunction
```

Do you think it would be possible to support using both plugins?

**Comment by mengelbrecht** [comment]
You are overwriting some settings in your example.
It works fine for me if you configure the `component_function` this way:
```viml
let g:lightline.component_function = { 'percent': 'NoScrollbarForLightline' }
```

**Comment by khughitt** [comment]
Ah, good catch! I didn't even make the connection between the two sections in my config.

Thanks for pointing that out! Your suggestion did the trick. :pray:
