### ISSUE TITLE
bufferline not updating when using vim-bbye or BClose

### ISSUE THREAD

**Issue by nstylo** [mengelbrecht/lightline-bufferline#46]
**Issue:**

Since I don't want to delete splits when deleting a buffer, I am running :Bclose offered by [vim-bbye](https://github.com/moll/vim-bbye). This sometimes leads to not updating the bufferline or even removing the whole bufferline itself.

With scripts like [BClose](https://vim.fandom.com/wiki/Deleting_a_buffer_without_closing_the_window) I have similar behaviour.

**How to reproduce:**

1. Install lightline-bufferline
2. install vim-bbye
3. open two buffers

![image](https://user-images.githubusercontent.com/45883614/78298179-a88ece80-7531-11ea-8a08-7c1ba2b45f8c.png)

4. Delete first buffer

![image](https://user-images.githubusercontent.com/45883614/78298194-ca885100-7531-11ea-8a34-6375625ab079.png)
 
As you can see, .vimrc is still in the bufferline although deleted. :e will refresh the bufferline.

![image](https://user-images.githubusercontent.com/45883614/78298402-86498080-7532-11ea-97f7-eb2279b62857.png)

5. Delete second buffer

![image](https://user-images.githubusercontent.com/45883614/78298375-77fb6480-7532-11ea-9155-0e20ed6f52e4.png)

Aaaand its gone....

Procedure might differ slightly. But essentially lightline-bufferline seems to have trouble with various kind of Bclose implementations.

**Comment by mengelbrecht** [comment]
Sorry for the late response. I somehow missed this issue. I will have a look at it and will try to reproduce it on my machine.

**Comment by mengelbrecht** [comment]
I could not reproduce it with neovim 0.4.3 and vim 8.1 together with vim-bbye and the Bclose script. The bufferline is correctly updated for me. Can you share a minimal vimrc config that reproduces the issue for you?

**Comment by mengelbrecht** [comment]
I am closing this due to the lack of feedback and because I cannot reproduce the issue. Feel free to reopen this issue if you are still experiencing this and can provide a minimal vimrc config that reproduces it.
