### ISSUE TITLE
No theming/coloring applied

### ISSUE THREAD

**Issue by qazip** [mengelbrecht/lightline-bufferline#48]
I just installed this plugin and enabled it but it seems like no theming and/or coloring is applied to the top bar (buffer bar now). Please see this screenshot.

![lightline_buffers](https://user-images.githubusercontent.com/16175716/80474986-b882ae00-8937-11ea-9530-add0c5a1329d.png)

I am using nvim and the important bits on my config file are as follows:

```

Plug 'mengelbrecht/lightline-bufferline'
Plug 'itchyny/lightline.vim'

set showtabline=2

let g:lightline#bufferline#show_number  = 1
let g:lightline#bufferline#shorten_path = 0
let g:lightline#bufferline#unnamed      = '[No Name]'
let g:lightline                  = {}
let g:lightline.tabline          = {'left': [['buffers']], 'right': [['close']]}
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}
```

What am I missing?

I'd like the buffer bar to resemble lightline. Most importantly, I would like the color of the selected buffer to be different.

**Comment by mengelbrecht** [comment]
The coloring is entirely done by lightline itself and not this plugin. If you choose e.g. the colorscheme `one` you see that the selected buffer color is different:
```viml
let g:lightline.colorscheme = 'one'
```

To specify custom colors you could create a new colorscheme for lightline. Maybe this issue in the lightline project helps: https://github.com/itchyny/lightline.vim/issues/61
