### ISSUE TITLE
modification marker "+" stays after saving

### ISSUE THREAD

**Issue by fdietze** [mengelbrecht/lightline-bufferline#5]
I broke it down to this small .vimrc (I'm using neovim):
```vim
set nocompatible
set laststatus=2
set hidden
set noshowmode


call plug#begin('~/.vim/bundle')
Plug 'itchyny/lightline.vim'
Plug 'mgee/lightline-bufferline'
call plug#end()

let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode' ], [  'buffers' ]],
      \ },
      \ 'component_expand': {
      \   'buffers' : 'lightline#bufferline#buffers'
      \ },
      \ 'component_type': {
      \   'buffers': 'tabsel'
      \ },
      \ }
```

To reproduce:

1. Open two files: `vim a b` (should start with the current buffer = a)
2. Insert new line: `o<Esc>`
3. Switch buffer two times `:bn` `:bn`
4. Save `:w`

The plus is still displayed for buffer a, even though it is not modified anymore. It disappears with another buffer change `:bn`.

**Comment by mengelbrecht** [comment]
This issue does not occur if the bufferline is used in the `tabline` component of lightline. Here the example from the readme file:
```vim
let g:lightline.tabline          = {'left': [['buffers']], 'right': [['close']]}
```

To fix your example you can trigger an update to lightline manually using this code in your vimrc:
```vim
autocmd BufWritePost * call lightline#update()
```

**Comment by aq2** [comment]
many thanks for your plugin - i find it really useful.

I have a similar problem to the one above, but reversed.

my modification marker **doesn't** appear when the buffer is modified.

It appears in the tabline okay, but not in the lightline bufferline - i need to switch to another buffer then back again to see modified icon in lightline.

![bufferline](https://cloud.githubusercontent.com/assets/13156649/24880001/98cc78e0-1e30-11e7-96a1-a68361addb5f.png)

running an autocmd every time i edit a buffer seems too expensive, so how do i fix?

**Comment by mengelbrecht** [comment]
@aq2 are you using the bufferline plugin in the tabline component and in the active.left / inactive.left section? This is what the screenshot shows, correct?

Can you post your (reduced) vimrc or lightline config to reproduce the issue?

**Comment by aq2** [comment]
hi, here's my mini vimrc

    set nocompatible
    set laststatus=2
    set showtabline=2

    execute pathogen#infect()
    " only lightline and bufferline in .vim/bundle

    let g:lightline = {
      \ 'active': {
      \   'left': [['buffers']]
      \ }	
    \ }

    let g:lightline#bufferline#modified  = ' @'
    let g:lightline.component_type   = {'buffers': 'tabsel'}
    let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
    let g:lightline.tabline          = {'left': [['buffers']], 'right': [['close']]}`

i changed the modified indicator to @, rather than a strange character to eliminate that possibility.

![modifiedbuffer](https://cloud.githubusercontent.com/assets/13156649/24928685/29ffda08-1efb-11e7-9fe6-d16f3c9ed4c1.png)

you can see the top  tabline displays @, but not the bottom lightline

thanks

**Comment by mengelbrecht** [comment]
@aq2 thanks for your vimrc.

I created an issue about this in lightline itchyny/lightline.vim#225 and it turns out that it is a limitation of the `component_expand` functionality which is used for the bufferline.
To fix it either use `buffers` in the `tabline` component of lightline or use the following `autocmd`:
```vim
autocmd BufWritePost,TextChanged,TextChangedI * call lightline#update()
```

**Comment by aq2** [comment]
thanks @mgee for your help - appreciated :)
