### ISSUE TITLE
How to remove 'X' in top right corner

### ISSUE THREAD

**Issue by jonleopard** [mengelbrecht/lightline-bufferline#52]
Hello! I was just curious how I can remove the close buffer 'x' that displays on the right side:
![Screenshot 2020-06-14 12 42 19](https://user-images.githubusercontent.com/2111234/84591200-cedbbf00-ae3c-11ea-93fc-3eed9f987abc.png)

I  tried removing the 'close' option from my config, but it still displays after removing it?
```
      \   'tabline': {
      \     'left': [ [ 'buffers' ] ],
      \     'right': [ [ 'close' ] ],  <--- still appears even after removing this
```

Thanks!

**Comment by mengelbrecht** [comment]
Try this setting:
```
'right': [ [] ]
```

**Comment by jonleopard** [comment]
That works like a charm! Thank you!
