### ISSUE TITLE
Is a option in README.md wrong?

### ISSUE THREAD

**Issue by gen4438** [mengelbrecht/lightline-bufferline#53]
I added options according to `README.md`, but it didn't work properly.

After I changed a value for `g:lightline.component_expand` as below, it worked.
Is this correct?

Before
```vim
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
```
After
```vim
let g:lightline.component_expand = {'buffers': 'lightline#buffer#bufferline'}
```

**Comment by mengelbrecht** [comment]
Did you use the updated example which was changed in ef674de5ca1c963ad12f04631ea58f90dbbc70da?
For me `lightline#bufferline#buffers` works and `lightline#buffer#bufferline` does not.

Can you post a minimal vimrc config that reproduces the issue?

**Comment by gen4438** [comment]
I mixed up your repository with another repository ([taohexxx/lightline-buffer](https://github.com/taohexxx/lightline-buffer)).
I forgot to run `PlugUpdate` after changing my vimrc.

I‘m so sorry to bother you.

**Comment by mengelbrecht** [comment]
No problem 😊
