### ISSUE TITLE
Buffer reordering

### ISSUE THREAD

**Issue by indev29** [mengelbrecht/lightline-bufferline#55]
Is it possible to reorder opened buffers on a tabline? Right now they are placed in the order of opening.

I think Airline couldn't do that because it used vim's buffer ids, I wonder if that is the case for Lightline also.

**Comment by mengelbrecht** [comment]
The only reordering this plugin supports is reversing the buffer order via the `lightline#bufferline#reverse_buffers` option.

**Comment by indev29** [comment]
Are there any plans to add more advanced reordering?

**Comment by mengelbrecht** [comment]
There is nothing planned in this area, sorry.
