### ISSUE TITLE
How to display arrow on Ubuntu OS?

### ISSUE THREAD

**Issue by edaplayer** [mengelbrecht/lightline-bufferline#60]
My OS is Ubuntu, I use lightline-buffline in my vim(terminal mode). but its outline is rectangle, not arrow.

**Comment by mengelbrecht** [comment]
Do you want to use powerline arrows as separators for the buffers? If this is the case it has to be configured in the lightline vim plugin since the separators are not handled in this plugin.
To use powerline arrows you can configure the separators like this (see e.g. https://github.com/itchyny/lightline.vim/issues/200):
```vim
let g:lightline = {
      ...
      \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
      \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
      \ }
```

**Comment by 123subhadeep** [comment]
Here's my config to display powerline arrows. I have a mac, I use vim over ssh session to a remote machine, I use iterm2 as my terminal. 

Do keep in mind that you might need to install powerline fonts first in your laptop.

let g:lightline = {
  \ 'colorscheme': 'gruvbox',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'relativepath', 'modified' ] ]
  \ },
  \ 'tabline': {
  \   'left': [ ['buffers'] ],
  \   'right': [ ['close'] ]
  \ },
  \ 'component_expand': {
  \   'buffers': 'lightline#bufferline#buffers'
  \ },
  \ 'component_type': {
  \   'buffers': 'tabsel'
  \ },
  \ 'separator': { 'left': '', 'right': '' },
  \ 'subseparator': { 'left': '', 'right': '' },
  \ 'component': {
  \   'lineinfo': ' %3l:%-2v',
  \ },
\ }

**Comment by mengelbrecht** [comment]
I am closing this issue because the question was answered. If the posted solutions do not work feel free to reopen the issue.
