### ISSUE TITLE
Option to show devicons before buffer ordinal number

### ISSUE THREAD

**Issue by noib3** [mengelbrecht/lightline-bufferline#63]
Basically title.

Edit: I got this working locally by moving lines 59-66 in autoload/lightline/bufferline.vim right before line 87.

**Comment by mengelbrecht** [comment]
I am not yet sure what the best approach is to make the buffer naming more flexible. Maybe a configurable template string which gets expanded with different components. However, I am not working on a solution currently so it is good that you got it working locally.

**Comment by mengelbrecht** [comment]
@noib3 I added the feature in #70. The following setting should work once the PR is merged:
```viml
let g:lightline#bufferline#icon_position = 'first'
```
