### ISSUE TITLE
Special case for handling index files

### ISSUE THREAD

**Issue by schontz** [mengelbrecht/lightline-bufferline#66]
It is common in NodeJS development to use `index.js` (or `index.ts`) file names. Sample project:

```
src
|- api
|  |- index.js
|- foo
|  |- index.js
```

If `api/index.js` is open, it just shows up as `index.js`, but this name is not informative. If both are open I get `a/index.js` and `f/index.js`. It would be preferred to have something like `api/i` to indicate the index file. I was reading up on `filename-modifiers`, but couldn't tell if there was an easy way to make it happen that way.

Any insights?

Thanks.

**Comment by schontz** [comment]
This gets me part of the way:

```
let g:lightline#bufferline#filename_modifier = ':s?\/index\.\(js\|jsx\|ts\|tsx\)$?.i?:t'
let g:lightline#bufferline#smart_path=0
```

This changes all `foo/index.js` to `foo.i`.  If I don't disable smart_path, then the files still show up as `index.js` until multiple index files are opened. This is an OK solution, but if other files have the same name, `:t` won't include their unique parts.

**Comment by mengelbrecht** [comment]
Unfortunately, I also don't have a perfect solution for this. However, here is another variant which leads to `api/i` as index file name because instead of a regular `/` a fraction slash is used which is not a path separator but almost looks like one (depending on your font):

```viml
let g:lightline#bufferline#filename_modifier = ':s?\/index\.\(js\|jsx\|ts\|tsx\)$?⁄i?'
let g:lightline#bufferline#smart_path = 0
```

**Comment by mengelbrecht** [comment]
I am closing this issue since there is a solution (albeit not perfect) for this special use-case.
