### ISSUE TITLE
Bufferline disappears after closing floating terminal

### ISSUE THREAD

**Issue by noib3** [mengelbrecht/lightline-bufferline#71]
The bufferline seems to disappear after closing a terminal window spawned with the [vim-floaterm](https://github.com/voldikss/vim-floaterm) plugin when two buffers are open. Weirdly enough, it doesn't disappear when three buffers are open.
![output](https://user-images.githubusercontent.com/59321248/100123707-19954480-2e7b-11eb-9351-fa3d0631dbd0.gif)

I have
```vim
let g:lightline#bufferline#show_number = 2
let g:lightline#bufferline#number_separator = ": "
let g:lightline#bufferline#enable_devicons = 1
let g:lightline#bufferline#icon_position = "first"
let g:lightline#bufferline#min_buffer_count = 2
let g:lightline#bufferline#clickable = 1
```
in my config files.

**Comment by noib3** [comment]
I just `:PlugUpdate`d to the latest commit but I'm still experiencing this issue.

**Comment by mengelbrecht** [comment]
Strange, after the latest commit I cannot reproduce it anymore...

As a workaround you can remove the `g:lightline#bufferline#min_buffer_count` option, which should fix it as well.

I will have a look at the `min_buffer_count` feature again to see what else might be causing problems.

**Comment by mengelbrecht** [comment]
@noib3 does this issue still occur if you try the branch `bugfix/disappearing-bufferline-2`?

**Comment by noib3** [comment]
@mengelbrecht `bugfix/disappearing-bufferline-2` fixed the issue.

**Comment by mengelbrecht** [comment]
@noib3 thanks for verifying. I merged the fix.
