### ISSUE TITLE
Spacing / margins?

### ISSUE THREAD

**Issue by adrian5** [mengelbrecht/lightline-bufferline#76]
Maybe I'm not seeing the obvious, but is there a straight-forward way to make tabs wider? I.e.:
```
|    foo.vim    |    context.js   |    style.css    |
```

**Comment by mengelbrecht** [comment]
@adrian5 you can try the `feature/margins` branch (PR #78) and set the following properties:
```viml
let g:lightline#bufferline#margin_left = 4
let g:lightline#bufferline#margin_right = 4
```

**Comment by adrian5** [comment]
Thanks, that does it!

**Comment by mengelbrecht** [comment]
@adrian5 I merged the branch
