### ISSUE TITLE
Feature Request - Tabline visible only when switching

### ISSUE THREAD

**Issue by yanisdb** [mengelbrecht/lightline-bufferline#79]
Hi,

Would it be possible to make the tabline visible only when switching buffers? That way I can see where I'm going when moving buffers and it doesn't take place when I am just editing the current one?

Thank you, and if you don't have, time tell me. I can take a look and make a pull request

**Comment by mengelbrecht** [comment]
Hi, can you describe the feature a little more? Do you want to hide the bufferline by default and as soon as you switch to a different buffer it is visible for *x* seconds and then hidden again?

**Comment by yanisdb** [comment]
Yes, exactly that would be exactly it. Something a bit like `alt+tab` on an operating system to switch windows but they work well without timer because it stays visible until you release the `alt` key. As most vim users probably use one key or `<leader>x`, it wouldn't work without a timer. But it would be enough for it to appear on `BufEnter`/`BufLeave` and disapear a few seconds after.
 
I tried looking into it but it is not quite working and I have no knowledge in vim script so its messy.
I tried adding that line:
```vimscript
function! lightline#bufferline#init()
  augroup lightline_bufferline
    autocmd!
    if s:min_buffer_count > 0
      autocmd BufEnter  * call <SID>auto_tabline()
      autocmd BufEnter  * call <SID>auto_hide_tabline() " <-- line I added
      autocmd BufDelete * call <SID>auto_tabline()
    endif
  augroup END
endfunction
```
And I added these too function:
```vimscript
function! Hide_tabline(timerid)
  set showtabline=0
endfun

function! s:auto_hide_tabline()
  call timer_start(2000, 'Hide_tabline')
endfunction
```
But it is not working that well, because if you switch once, then switch again before the x seconds have passed, the buffer line will disappear to fast. The timer would need to be reset if you switch again before it ended. 
We would need something like `timer_stop(timerid)` but I don't know where to put that line.

**Comment by mengelbrecht** [comment]
I think this functionality is best suited outside of this plugin since it solves a very specific use-case.
If you place the following code in your vimrc it should work:
```viml
set showtabline=0
let s:tabline_timer = -1

function! s:auto_hide_tabline()
  if s:tabline_timer > -1
    call timer_stop(s:tabline_timer)
  endif
  set showtabline=2
  let s:tabline_timer = timer_start(2000, 'HideTabline')
endfunction

function! HideTabline(timer)
  set showtabline=0
  let s:tabline_timer = -1
endfunction

autocmd BufEnter,BufLeave * call <SID>auto_hide_tabline()
```

Edit: I updated the code to reset the timer id after it has finished.

**Comment by yanisdb** [comment]
Thank you, it seems very clean and perfect for my use.

**Comment by mengelbrecht** [comment]
@yanisdb I added this feature to the plugin, you can use it like this:
```viml
let g:lightline#bufferline#auto_hide = 2000
```
