### ISSUE TITLE
Change color of the modified buffers

### ISSUE THREAD

**Issue by max-baz** [mengelbrecht/lightline-bufferline#8]
Having a `+` symbol to indicate modified buffers is good, but showing the modified buffers in a different color would be awesome. Airline does that, I hope it is possible to achieve with lightline too (presumably via `component_expand`)?

![modified](https://user-images.githubusercontent.com/1177900/32148407-cd137ab2-bcf6-11e7-840d-e5b49969cb36.gif)

**Comment by mengelbrecht** [comment]
I don't think that this is possible using lightline (see https://github.com/itchyny/lightline.vim/issues/249).

The only way to change the color is via the `component_type` option by setting it to `warning` or `error`. However this would apply to all buffers and not just the modified ones. Also for the bufferline to work correctly the `component_type` has to be set to `tabsel`.

**Comment by max-baz** [comment]
Oh that's unfortunate that there is a limitation that `component_type` has to be set to `tabsel`. Thanks for the quick response.

**Comment by max-baz** [comment]
After I discovered `#lightline-problem-12` in `:h lightline`, I realized that this is _kind of_ possible, but can't be done in the plugin properly to satisfy everyone.

-----------

For the curious minds that stumble upon this ticket in the future, here's how and why:

One could add this simple snippet to `s:get_buffer_name`:

```
  exe 'hi BufferlineModifiedColor guibg=#a89984 guifg=#1247d0'
  let l:name = substitute(l:name, '%', '%%', 'g')
  if getbufvar(a:buffer, '&mod')
    let l:name = '%#BufferlineModifiedColor#' . l:name
  endif
  return l:name
```

and get the following result:

![modified](https://user-images.githubusercontent.com/1177900/32353173-9dd2707e-c024-11e7-8d9e-cd0113b698f4.gif)

The issues with this approach:

1. The plugin has access to only the inner part of the icon, not the separator symbols, so if you change background color, it will only have effect inside the red box:

![image](https://user-images.githubusercontent.com/1177900/32353281-0d81a534-c025-11e7-8e69-fa726a722a27.png)

2. The lightline themes don't define colors for modified buffers (contrary to airline themes), so it would be really hard to guess the correct color that would look good on an unknown theme.

3. Coloring is even more complicated if you consider that both current and non-current buffers can be modified, and they need to be colored differently.

So now you know 🙂

**Comment by PezCoder** [comment]
@maximbaz Thank you for the explanation.!

In my personal opinion, I like the changing tab color to be a great indicator to know if I've saved the tabs or not. It has become so instinctive as a representation to save the file when I see it.

I looked at how some of the other editors does it & realised if I can go with another alternatives than color:
**Sublime:**
<img width="280" alt="Screenshot 2021-03-22 at 4 31 19 AM" src="https://user-images.githubusercontent.com/8057916/111924126-da919b80-8ac8-11eb-9541-5310f2e82bb4.png">

**VSCode:**
<img width="432" alt="Screenshot 2021-03-22 at 4 41 02 AM" src="https://user-images.githubusercontent.com/8057916/111924127-dcf3f580-8ac8-11eb-9f27-51fa0b9b8918.png">

They show this dot at the end of the name to signifies that there are some unsaved changes, if somebody is interested in that just do:
```
let g:lightline#bufferline#modified = ' ●'
```

For me personally, the dot doesn't feel like an obvious indicator for the same, so I tried these.

**Tilde:** ` ~`
<img width="440" alt="Screenshot 2021-03-22 at 4 39 27 AM" src="https://user-images.githubusercontent.com/8057916/111924181-26444500-8ac9-11eb-9c6b-e5b45e3f7e22.png">

**Pencil:** `✎`
<img width="451" alt="Screenshot 2021-03-22 at 4 35 42 AM" src="https://user-images.githubusercontent.com/8057916/111924187-2f351680-8ac9-11eb-914e-d24c2ca2b2fe.png">

**Cross:** `✕`
<img width="353" alt="Screenshot 2021-03-22 at 4 35 22 AM" src="https://user-images.githubusercontent.com/8057916/111924193-3825e800-8ac9-11eb-80d4-f88951467076.png">

**Star:** ` ✱`
<img width="408" alt="Screenshot 2021-03-22 at 4 50 08 AM" src="https://user-images.githubusercontent.com/8057916/111924355-28f36a00-8aca-11eb-962d-d5eb7b5fb3bb.png">


I'll mostly go ahead with 'pencil' for now, I'm sure we can go with either & the muscle memory shall develop with either of them. It's all about aesthetics in the end.
