### ISSUE TITLE
Closed buffer still appears in bufferline

### ISSUE THREAD

**Issue by diegoulloao** [mengelbrecht/lightline-bufferline#80]
When I close a buffer the associated tab doesn't disappears.
I'm doing something wrong or do I have some configuration value missing?

I'm using NeoVim

**Comment by mengelbrecht** [comment]
Can you provide a minimal vimrc to reproduce the issue? Are you using the latest version?

**Comment by diegoulloao** [comment]
Here is my reduced `.vimrc`. I'm using the latest version of lightline-bufferline with nvim 0.4.4

```vim
" Theme settings
let lightline_theme="16color"

set clipboard=unnamed
set showmatch
set laststatus=2

call plug#begin('~/.vim/plugged')
" IDE
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'unkiwii/vim-nerdtree-sync'
Plug 'mengelbrecht/lightline-bufferline'
call plug#end()

" Lightline
set showtabline=2
let g:lightline#bufferline#show_number=2
let g:lightline#bufferline#icon_position="right"
" Put cool lightline separators
let g:lightline#bufferline#clickable=1

" Reload Lightline
function! LightlineReload()
  call lightline#init()
  call lightline#colorscheme()
  call lightline#update()
endfunction

let g:lightline = {
      \ 'colorscheme': lightline_theme,
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \   'gitbranch': 'gitbranch#name'
      \ },
      \ 'tabline': {
      \   'left': [ ['buffers'] ],
      \   'right': [ ['close'] ]
      \ },
      \ 'component_expand': {
      \   'buffers': 'lightline#bufferline#buffers'
      \ },
      \ 'component_type': {
      \   'buffers': 'tabsel'
      \ },
      \ 'component_raw': {
      \   'buffers': 1
      \ }
      \ }

" Filename Lightline
function! LightlineFilename()
  let root = fnamemodify(get(b:, 'git_dir'), ':h')
  let path = expand('%:p')
  if path[:len(root)-1] ==# root
    return path[len(root)+1:]
  endif
  return expand('%')
endfunction

" After a re-source, reload the lightline theme
call LightlineReload()

" Fix autoload when file changes
au FocusGained,BufEnter * :checktime
```

**Comment by mengelbrecht** [comment]
Unfortunately I cannot reproduce the issue. Everytime I close a buffer with `:bdelete` the bufferline is updated correctly.
Does it work if you manually update lightline after deleting the buffer using the snippet in this [post](https://github.com/mengelbrecht/lightline-bufferline/issues/51#issuecomment-629426866)?

**Comment by diegoulloao** [comment]
The command I trigger is `:quit`, which is mapped through `<Leader>q` keys. Has anything to do with this?
`:bdelete` works but `:quit` not.

**Comment by mengelbrecht** [comment]
The `:quit` command is for closing the window and not the buffer. After triggering `:quit` you can inspect the vim buffer list using `:ls` and see that the buffer is still open.

**Comment by diegoulloao** [comment]
So I should use `:bdelete` instead of `:quit`. I understand.
Will be good to mention this in the README for those who don't know about.

Thanks and sorry for the false alarm.
