### ISSUE TITLE
Bufferline not hidden after deleting buffer in vertical split

### ISSUE THREAD

**Issue by noib3** [mengelbrecht/lightline-bufferline#82]
I have `g:lightline#bufferline#min_buffer_count` set to 2, but the bufferline remains visible if I `:bd` a buffer in a vertical split. The following gif shows the problem with an example:
![output](https://user-images.githubusercontent.com/59321248/106363803-0b581e80-632b-11eb-9fe4-cb096a51ac99.gif)

**Comment by mengelbrecht** [comment]
@noib3 does this issue still occur if you try the branch `bugfix/delay-event-handler`?

**Comment by noib3** [comment]
@mengelbrecht no, that branch works fine. Should I keep using that or will some fix get merged into master?

**Comment by mengelbrecht** [comment]
@noib3 I merged the fix to master.
