### ISSUE TITLE
Feature request: buffer reordering and general buffer manupulation in tabline

### ISSUE THREAD

**Issue by ghost** [mengelbrecht/lightline-bufferline#85]
Feature request: make it possible to visually reorder buffers in tabline.

Since (I suppose) most people (me included, at least) are using this plugin to unify experience between simple editors and vim and not for a minute be involved into thinking about buffers or tabs, there is a need to be able to reorder buffers. I am talking about something like `:tabmove` for tabs. It doesn't need to represent real buffer order as per `:ls`, because it would be [impossible to implement](https://vi.stackexchange.com/a/466).

What I suggest is:
* create a level of abstraction above `:ls` (I don't know if the plugin already does that, sorry) which would be a list that represents order
* maintain this custom list and allow to edit this list:
    * provide something to map a key to that would move current buffer left/right (like `:tabmove +1/-1`)
        * if it's first/last in the list, stop moving it (e.g. trying to move the leftmost buffer to the left is nop)
    * provide some command that would open (in sense of `:edit`) file in the next buffer to the right: that is, instead of opening file god knows where (which is what `:edit` does, which opens based on number which the buffer is assigned (great idea, isn't it?)), open it in the direct next buffer to the right of the current buffer: that is, open the file, see which number it gets and edit the plugin's buffer list accordingly to point at the right buffer in global buffer list
    * same with closing the buffer
    * probably something else I am not accounting for
* display the plugin's list instead of the global list

Now that I've written all that, it started with a desire to have movable buffers in the list, but now it feels like this feature has to be twice the scope of this plugin.

Anyway, what do you think?

**Comment by mengelbrecht** [comment]
Hi @avemilia, thanks for your feature suggestion. That functionality sounds interesting. However, I don't want to increase the complexity of the plugin and keep it small. Therefore it is out of scope for this plugin, sorry.
