### ISSUE TITLE
i can't see tabs in ligthline-bufferline

### ISSUE THREAD

**Issue by Ezequiel-Vega** [mengelbrecht/lightline-bufferline#87]
Hi, i have a problem with lightline-buffer, i can't see the buffer tabs at the top

**Comment by mengelbrecht** [comment]
Hi @Ezequiel-Vega, do you mean that you don't see buffers or don't see tabs? This plugin is only for displaying buffers.

Did you set the plugin up according to the readme? If so, did you set `set showtabline=2` in your vim config to always display the buffers?

In case that setting does not change anything, please provide a vim config (preferably minimized to illustrate the issue) so I can have a more detailed look.

**Comment by mengelbrecht** [comment]
I assume that you solved the issue, otherwise feel free to reopen it.
