### ISSUE TITLE
Options don't effect how the buffer tabs look.

### ISSUE THREAD

**Issue by arg3t** [mengelbrecht/lightline-bufferline#88]
Hi, the options do not change how the tabs on the top of the page look. I have tested nearly all the settings in the README and none of them change how the tabs look. You can see a demonstration in this picture.
![image](https://user-images.githubusercontent.com/30830979/113402582-ea08c280-93ad-11eb-990c-8a3288896f3c.png)
I copied and pasted some else's configs thinking I did something wrong ([here](https://github.com/pirey/dotfiles/blob/master/home/.config/nvim/plugin-options/lightline.vim)) but that didn't change anything. My configuration for lightline and this plugin is in my [dotfiles](https://github.com/theFr1nge/dotfiles/tree/main/local/share/vim/plugin)

**Comment by mengelbrecht** [comment]
@theFr1nge did you commit the lightline config to your dotfiles repository? I could not find any configuration for lightline or lightline-bufferline.

**Comment by arg3t** [comment]
Oops, my bad, forgot to push the changes. I just committed everything.

**Comment by mengelbrecht** [comment]
@theFr1nge there is still no lightline config...

**Comment by arg3t** [comment]
@mengelbrecht I am really sorry about that, some mixup happened with my gitignores and my changes didn't get pushed. I definitely fixed it this time though.

**Comment by mengelbrecht** [comment]
Never mind. How do you source the plugin configuration files in the `local/share/vim/plugin` folder? I saw that you only explicitly source the `plugins.vim` file [here](https://github.com/theFr1nge/dotfiles/blob/c524a0c01fdf52563c10c9ebad40f73cb4addbd5/config/vim/vimrc#L22).

**Comment by arg3t** [comment]
Vim automatically sources every file in that directory. I explicitly sourced plugins.vim because some of my settings in my vimrc depend on the plugins.

**Comment by mengelbrecht** [comment]
@theFr1nge I could not reproduce the issue. However, I had to manually source the files in the `plugin` folder, as vim did not load them automatically.
I suggest that you move the lightline and lightline-bufferline settings directly into your vimrc config to see if the issue is caused by the way your dotfiles repository and vim configuration files are setup.

If that does not work please create a minimal vimrc config which reproduces the issue so I can have a more detailed look.

**Comment by arg3t** [comment]
Yep... that was it. Apparently vim sources ~/.config/vim/plugins and not ~/.local/share/vim/plugins on startup. I moved the folder over there and it is working a like charm. Thanks for your help and making such a great plugin!
