### ISSUE TITLE
Feature Request: Honor tabs when auto-hiding tabline

### ISSUE THREAD

**Issue by potamides** [mengelbrecht/lightline-bufferline#89]
Hi, first thank you for this useful plugin! I have configured lightline-bufferline like [this](https://github.com/potamides/dotfiles/blob/6728f9ac16e8e4669fb022f8211bb938076981ff/.config/nvim/init.vim#L189-L230):
```vim
let g:lightline.tabline = {'left': [['buffers']], 'right': [['tabs']]}
let g:lightline#bufferline#min_buffer_count=2
```
That is, show buffers on the left and tabs on the right and automatically show the tabline when there are multiple buffers. This works fine, but I'd also like to see the tabline when there's only one buffer but multiple tabs. To achieve this right now I use the following autocommand:
```vim
autocmd OptionSet showtabline if v:option_new == 0 | set showtabline=1 | endif
```
This works, but I don't think this is a nice solution. Is there some interest in making this configurable in the plugin itself?

**Comment by mengelbrecht** [comment]
Hi @potamides, I created PR #90 which implements this feature. Can you test it and see if it behaves as expected?

**Comment by potamides** [comment]
Of course, thank you very much!

**Comment by mengelbrecht** [comment]
@potamides this feature has been merged into master
