### ISSUE TITLE
Buffers are not displayed

### ISSUE THREAD

**Issue by NiYanhhhhh** [mengelbrecht/lightline-bufferline#94]
Hi, after I setup the lightline-bufferline referring to the readme, I didn't see the buffers in tabline, which is shown in the picture below.
![2021-08-06_15-39](https://user-images.githubusercontent.com/55988662/128475386-e7f98b5a-fdb9-412d-a7f4-3d838874e6d8.png)

The output of ```lightline#bufferline#buffers```:
![image](https://user-images.githubusercontent.com/55988662/128475875-a95dd1d8-9ba6-42a5-a02d-b6df54e87cd4.png)

**Comment by mengelbrecht** [comment]
Can you share your complete lightline configuration so that I can have a look (the screenshot shows only a partial config)?

**Comment by NiYanhhhhh** [comment]
Complete lightline configuration: [https://pastebin.com/EJWsExUF](https://pastebin.com/EJWsExUF),
and my colorscheme: [https://pastebin.com/1kJNLMu0](https://pastebin.com/1kJNLMu0)

**Comment by NiYanhhhhh** [comment]
Well, I find a foolish mistake... I put my ```component_expand``` pair in ```g:lightline.tabline```, which is actually in ```g:lightline```.
Anyway, thanks a lot for replying.
\_(:з」∠)\_
